export const LOADING_HOTELS = 'LOADING_HOTELS';
export const LOADING_HOTELS_SUCCESS = 'LOADING_HOTELS_SUCCESS';
export const LOADING_HOTELS_ERR = 'LOADING_HOTELS_ERR';
export const FILTER_HOTELS = 'FILTER_HOTELS';